/**
 * Constants for action names.
 */

export const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';


export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';


export const LOGOUT = 'LOGOUT';


export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_RESET = 'REGISTER_RESET';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';


export const TEAM_FETCH_SUCCESS = 'TEAM_FETCH_SUCCESS';

export const TEAMS_FETCH_START = 'TEAMS_FETCH_START';
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS';
