/**
 * Constants for action names.
 */


export const GAME_ADD_FAIL = 'GAME_ADD_FAIL';
export const GAME_ADD_START = 'GAME_ADD_START';
export const GAME_ADD_SUCCESS = 'GAME_ADD_SUCCESS';
export const GAME_FORM_RESET = 'GAME_FORM_RESET';


export const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';


export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';


export const LOGOUT = 'LOGOUT';


export const PLAYER_ADD_FAIL = 'PLAYER_ADD_FAIL';
export const PLAYER_ADD_START = 'PLAYER_ADD_START';
export const PLAYER_ADD_SUCCESS = 'PLAYER_ADD_SUCCESS';
export const PLAYER_FORM_RESET = 'PLAYER_FORM_RESET';


export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_RESET = 'REGISTER_RESET';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';


export const TEAM_ADD_FAIL = 'TEAM_ADD_FAIL';
export const TEAM_ADD_START = 'TEAM_ADD_START';
export const TEAM_ADD_SUCCESS = 'TEAM_ADD_SUCCESS';
export const TEAM_FETCH_SUCCESS = 'TEAM_FETCH_SUCCESS';
export const TEAM_FORM_RESET = 'TEAM_FORM_RESET';

export const TEAMS_FETCH_START = 'TEAMS_FETCH_START';
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS';

export const TEAM_GAMES_FETCH_SUCCESS = 'TEAM_GAMES_FETCH_SUCCESS';

export const TEAM_PLAYERS_FETCH_SUCCESS = 'TEAM_PLAYERS_FETCH_SUCCESS';
